version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "https://api.example.com"  # or "/api" if proxying
        VITE_USE_MOCK: "true"                         # set to "false" for real API
    image: envmonitor:prod
    ports:
      - "8080:80"
    restart: unless-stopped